In [1]:
import battle

In [2]:
b = battle.Battle('gen9-randombattle/gen9randombattle-2631360263.json')

In [3]:
print(b.teams_full)

[{'Delphox': {'name': 'Delphox', 'species': 'Delphox', 'speciesId': 'delphox', 'gender': 'F', 'shiny': False, 'level': 84, 'moves': ['fireblast', 'grassknot', 'focusblast', 'psyshock'], 'ability': 'Blaze', 'evs': {'hp': 85, 'atk': 0, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 0, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Choice Specs', 'teraType': 'Fire', 'role': 'Fast Attacker', 'bvs': {'hp': 75, 'atk': 69, 'def': 72, 'spa': 114, 'spd': 100, 'spe': 104}, 'stats': {'hp': 263, 'atk': 120, 'def': 169, 'spa': 240, 'spd': 216, 'spe': 223}, 'types': ['Fire', 'Psychic']}, 'Indeedee': {'name': 'Indeedee', 'species': 'Indeedee-F', 'speciesId': 'indeedeef', 'gender': 'F', 'shiny': False, 'level': 90, 'moves': ['hypervoice', 'psyshock', 'shadowball', 'calmmind'], 'ability': 'Psychic Surge', 'evs': {'hp': 85, 'atk': 0, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 0, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Life Orb', 'teraType': 'Psychic', 'role': 'Fast Attacker', 'bvs': {'hp': 70, 'atk': 55, 'def': 65, 'spa': 95, 'spd': 105, 'spe': 85}, 'stats': {'hp': 272, 'atk': 104, 'def': 168, 'spa': 222, 'spd': 240, 'spe': 204}, 'types': ['Psychic', 'Normal']}, 'Skarmory': {'name': 'Skarmory', 'species': 'Skarmory', 'speciesId': 'skarmory', 'gender': 'M', 'shiny': False, 'level': 80, 'moves': ['whirlwind', 'bravebird', 'spikes', 'roost'], 'ability': 'Sturdy', 'evs': {'hp': 85, 'atk': 85, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 31, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Rocky Helmet', 'teraType': 'Dragon', 'role': 'Bulky Support', 'bvs': {'hp': 65, 'atk': 80, 'def': 140, 'spa': 40, 'spd': 70, 'spe': 70}, 'stats': {'hp': 235, 'atk': 174, 'def': 270, 'spa': 110, 'spd': 158, 'spe': 158}, 'types': ['Steel', 'Flying']}, 'Wugtrio': {'name': 'Wugtrio', 'species': 'Wugtrio', 'speciesId': 'wugtrio', 'gender': 'M', 'shiny': False, 'level': 91, 'moves': ['liquidation', 'aquajet', 'throatchop', 'stompingtantrum'], 'ability': 'Gooey', 'evs': {'hp': 85, 'atk': 85, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 31, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Choice Band', 'teraType': 'Dark', 'role': 'Fast Attacker', 'bvs': {'hp': 35, 'atk': 100, 'def': 50, 'spa': 50, 'spd': 70, 'spe': 120}, 'stats': {'hp': 212, 'atk': 234, 'def': 143, 'spa': 143, 'spd': 179, 'spe': 270}, 'types': ['Water']}, 'Tauros': {'name': 'Tauros', 'species': 'Tauros-Paldea-Aqua', 'speciesId': 'taurospaldeaaqua', 'gender': 'M', 'shiny': False, 'level': 81, 'moves': ['stoneedge', 'closecombat', 'wavecrash', 'aquajet'], 'ability': 'Intimidate', 'evs': {'hp': 85, 'atk': 85, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 31, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Choice Band', 'teraType': 'Water', 'role': 'Wallbreaker', 'bvs': {'hp': 75, 'atk': 110, 'def': 105, 'spa': 30, 'spd': 70, 'spe': 100}, 'stats': {'hp': 254, 'atk': 225, 'def': 217, 'spa': 95, 'spd': 160, 'spe': 209}, 'types': ['Fighting', 'Water']}, 'Victreebel': {'name': 'Victreebel', 'species': 'Victreebel', 'speciesId': 'victreebel', 'gender': 'M', 'shiny': False, 'level': 90, 'moves': ['powerwhip', 'sunnyday', 'sludgewave', 'weatherball'], 'ability': 'Chlorophyll', 'evs': {'hp': 85, 'atk': 85, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 31, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Life Orb', 'teraType': 'Fire', 'role': 'Fast Attacker', 'bvs': {'hp': 80, 'atk': 105, 'def': 65, 'spa': 100, 'spd': 70, 'spe': 70}, 'stats': {'hp': 290, 'atk': 240, 'def': 168, 'spa': 231, 'spd': 177, 'spe': 177}, 'types': ['Grass', 'Poison']}}, {'Wigglytuff': {'name': 'Wigglytuff', 'species': 'Wigglytuff', 'speciesId': 'wigglytuff', 'gender': 'F', 'shiny': False, 'level': 96, 'moves': ['wish', 'protect', 'dazzlinggleam', 'fireblast'], 'ability': 'Competitive', 'evs': {'hp': 85, 'atk': 0, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 0, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Leftovers', 'teraType': 'Poison', 'role': 'Bulky Support', 'bvs': {'hp': 140, 'atk': 70, 'def': 45, 'spa': 85, 'spd': 50, 'spe': 45}, 'stats': {'hp': 424, 'atk': 139, 'def': 141, 'spa': 218, 'spd': 150, 'spe': 141}, 'types': ['Normal', 'Fairy']}, 'Lokix': {'name': 'Lokix', 'species': 'Lokix', 'speciesId': 'lokix', 'gender': 'M', 'shiny': False, 'level': 82, 'moves': ['firstimpression', 'uturn', 'knockoff', 'suckerpunch'], 'ability': 'Tinted Lens', 'evs': {'hp': 85, 'atk': 85, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 31, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Silver Powder', 'teraType': 'Bug', 'role': 'Fast Attacker', 'bvs': {'hp': 71, 'atk': 102, 'def': 78, 'spa': 52, 'spd': 55, 'spe': 92}, 'stats': {'hp': 251, 'atk': 214, 'def': 175, 'spa': 132, 'spd': 137, 'spe': 198}, 'types': ['Bug', 'Dark']}, 'Mandibuzz': {'name': 'Mandibuzz', 'species': 'Mandibuzz', 'speciesId': 'mandibuzz', 'gender': 'F', 'shiny': False, 'level': 85, 'moves': ['toxic', 'defog', 'foulplay', 'roost'], 'ability': 'Overcoat', 'evs': {'hp': 85, 'atk': 0, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 0, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Heavy-Duty Boots', 'teraType': 'Steel', 'role': 'Bulky Support', 'bvs': {'hp': 110, 'atk': 65, 'def': 105, 'spa': 55, 'spd': 95, 'spe': 80}, 'stats': {'hp': 326, 'atk': 115, 'def': 227, 'spa': 142, 'spd': 210, 'spe': 185}, 'types': ['Dark', 'Flying']}, 'Snorlax': {'name': 'Snorlax', 'species': 'Snorlax', 'speciesId': 'snorlax', 'gender': 'M', 'shiny': False, 'level': 82, 'moves': ['bodyslam', 'curse', 'crunch', 'earthquake'], 'ability': 'Thick Fat', 'evs': {'hp': 85, 'atk': 85, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 31, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Leftovers', 'teraType': 'Ground', 'role': 'Bulky Setup', 'bvs': {'hp': 160, 'atk': 110, 'def': 65, 'spa': 65, 'spd': 110, 'spe': 30}, 'stats': {'hp': 397, 'atk': 228, 'def': 154, 'spa': 154, 'spd': 228, 'spe': 96}, 'types': ['Normal']}, 'Torterra': {'name': 'Torterra', 'species': 'Torterra', 'speciesId': 'torterra', 'gender': 'M', 'shiny': False, 'level': 78, 'moves': ['headlongrush', 'shellsmash', 'rockblast', 'bulletseed'], 'ability': 'Overgrow', 'evs': {'hp': 85, 'atk': 85, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 31, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Loaded Dice', 'teraType': 'Ground', 'role': 'Setup Sweeper', 'bvs': {'hp': 95, 'atk': 109, 'def': 105, 'spa': 75, 'spd': 85, 'spe': 56}, 'stats': {'hp': 276, 'atk': 215, 'def': 209, 'spa': 162, 'spd': 178, 'spe': 132}, 'types': ['Grass', 'Ground']}, 'Mienshao': {'name': 'Mienshao', 'species': 'Mienshao', 'speciesId': 'mienshao', 'gender': 'F', 'shiny': True, 'level': 83, 'moves': ['closecombat', 'fakeout', 'uturn', 'knockoff'], 'ability': 'Regenerator', 'evs': {'hp': 85, 'atk': 85, 'def': 85, 'spa': 85, 'spd': 85, 'spe': 85}, 'ivs': {'hp': 31, 'atk': 31, 'def': 31, 'spa': 31, 'spd': 31, 'spe': 31}, 'item': 'Assault Vest', 'teraType': 'Dark', 'role': 'AV Pivot', 'bvs': {'hp': 65, 'atk': 125, 'def': 60, 'spa': 95, 'spd': 60, 'spe': 105}, 'stats': {'hp': 244, 'atk': 255, 'def': 147, 'spa': 205, 'spd': 147, 'spe': 222}, 'types': ['Fighting']}}]

In [4]:
len(b.teams_full)

2

In [5]:
import pandas as pd

In [ ]:
row = {}
for player in [1,2]:
    i = 1
    for key,value in b.teams_full[player-1].items():
        prefix = f'p{player}_mon{i}_'

        for stat in value['stats']:
            row[prefix + stat] = [value['stats'][stat]]
        row[prefix + 'types'] = [value['types']] if type(value['types']) == list else [[value['types']]]
        i+=1
row['winner'] = [1] if b.winner == b.p1 else [2]
print(row)

{'p1_mon1_hp': [263], 'p1_mon1_atk': [120], 'p1_mon1_def': [169], 'p1_mon1_spa': [240], 'p1_mon1_spd': [216], 'p1_mon1_spe': [223], 'p1_mon1_types': [['Fire', 'Psychic']], 'p1_mon2_hp': [272], 'p1_mon2_atk': [104], 'p1_mon2_def': [168], 'p1_mon2_spa': [222], 'p1_mon2_spd': [240], 'p1_mon2_spe': [204], 'p1_mon2_types': [['Psychic', 'Normal']], 'p1_mon3_hp': [235], 'p1_mon3_atk': [174], 'p1_mon3_def': [270], 'p1_mon3_spa': [110], 'p1_mon3_spd': [158], 'p1_mon3_spe': [158], 'p1_mon3_types': [['Steel', 'Flying']], 'p1_mon4_hp': [212], 'p1_mon4_atk': [234], 'p1_mon4_def': [143], 'p1_mon4_spa': [143], 'p1_mon4_spd': [179], 'p1_mon4_spe': [270], 'p1_mon4_types': [['Water']], 'p1_mon5_hp': [254], 'p1_mon5_atk': [225], 'p1_mon5_def': [217], 'p1_mon5_spa': [95], 'p1_mon5_spd': [160], 'p1_mon5_spe': [209], 'p1_mon5_types': [['Fighting', 'Water']], 'p1_mon6_hp': [290], 'p1_mon6_atk': [240], 'p1_mon6_def': [168], 'p1_mon6_spa': [231], 'p1_mon6_spd': [177], 'p1_mon6_spe': [177], 'p1_mon6_types': [['Grass', 'Poison']], 'p2_mon1_hp': [424], 'p2_mon1_atk': [139], 'p2_mon1_def': [141], 'p2_mon1_spa': [218], 'p2_mon1_spd': [150], 'p2_mon1_spe': [141], 'p2_mon1_types': [['Normal', 'Fairy']], 'p2_mon2_hp': [251], 'p2_mon2_atk': [214], 'p2_mon2_def': [175], 'p2_mon2_spa': [132], 'p2_mon2_spd': [137], 'p2_mon2_spe': [198], 'p2_mon2_types': [['Bug', 'Dark']], 'p2_mon3_hp': [326], 'p2_mon3_atk': [115], 'p2_mon3_def': [227], 'p2_mon3_spa': [142], 'p2_mon3_spd': [210], 'p2_mon3_spe': [185], 'p2_mon3_types': [['Dark', 'Flying']], 'p2_mon4_hp': [397], 'p2_mon4_atk': [228], 'p2_mon4_def': [154], 'p2_mon4_spa': [154], 'p2_mon4_spd': [228], 'p2_mon4_spe': [96], 'p2_mon4_types': [['Normal']], 'p2_mon5_hp': [276], 'p2_mon5_atk': [215], 'p2_mon5_def': [209], 'p2_mon5_spa': [162], 'p2_mon5_spd': [178], 'p2_mon5_spe': [132], 'p2_mon5_types': [['Grass', 'Ground']], 'p2_mon6_hp': [244], 'p2_mon6_atk': [255], 'p2_mon6_def': [147], 'p2_mon6_spa': [205], 'p2_mon6_spd': [147], 'p2_mon6_spe': [222], 'p2_mon6_types': [['Fighting']], 'winner': [2]}

In [7]:
pd.DataFrame(row)

,p1_mon1_hp,p1_mon1_atk,p1_mon1_def,p1_mon1_spa,p1_mon1_spd,p1_mon1_spe,p1_mon1_types,p1_mon2_hp,p1_mon2_atk,p1_mon2_def,...,p2_mon5_spe,p2_mon5_types,p2_mon6_hp,p2_mon6_atk,p2_mon6_def,p2_mon6_spa,p2_mon6_spd,p2_mon6_spe,p2_mon6_types,winner
0,263,120,169,240,216,223,"[Fire, Psychic]",272,104,168,...,132,"[Grass, Ground]",244,255,147,205,147,222,[Fighting],2

In [8]:
df = pd.DataFrame(row).drop(labels=[0],axis=0)

In [9]:
import os

folder_path = "gen9-randombattle"

In [10]:
for filename in os.listdir(folder_path):
    if filename.endswith(".json"):
        file_path = os.path.join(folder_path, filename)
        b = battle.Battle(file_path)
        row = {}
        for player in [1,2]:
            i = 1
            for key,value in b.teams_full[player-1].items():
                prefix = f'p{player}_mon{i}_'

                for stat in value['stats']:
                    row[prefix + stat] = [value['stats'][stat]]
                row[prefix + 'types'] = [value['types']] if type(value['types']) == list else [[value['types']]]
                i+=1
        row['winner'] = [1] if b.winner == b.p1 else [2]
        df = pd.concat([df, pd.DataFrame(row)], ignore_index=True)

In [11]:
df.head(10)

,p1_mon1_hp,p1_mon1_atk,p1_mon1_def,p1_mon1_spa,p1_mon1_spd,p1_mon1_spe,p1_mon1_types,p1_mon2_hp,p1_mon2_atk,p1_mon2_def,...,p2_mon5_spe,p2_mon5_types,p2_mon6_hp,p2_mon6_atk,p2_mon6_def,p2_mon6_spa,p2_mon6_spd,p2_mon6_spe,p2_mon6_types,winner
0,264,235,172,180,164,180,"[Water, Fighting]",262,140,291,...,141,"[Rock, Fairy]",233,139,201,183,194,174,"[Steel, Fairy]",2
1,246,198,153,211,160,241,"[Water, Dark]",259,302,142,...,174,[Fighting],257,165,162,234,162,170,"[Electric, Poison]",2
2,269,164,150,251,188,213,"[Poison, Psychic]",258,224,193,...,207,[Bug],246,92,172,189,189,311,"[Electric, Grass]",1
3,254,104,224,249,180,164,"[Grass, Ghost]",253,114,139,...,259,[Grass],265,105,175,145,175,137,[Normal],1
4,263,216,159,149,159,241,[Normal],216,211,293,...,100,[Water],296,247,186,166,197,150,"[Ghost, Grass]",2
5,284,241,270,110,176,110,[Rock],321,289,190,...,173,[Fighting],257,105,316,188,325,125,"[Rock, Steel]",2
6,352,161,200,236,200,108,"[Grass, Dragon]",302,270,230,...,172,"[Ghost, Dragon]",284,93,226,226,402,138,[Ice],2
7,343,168,144,120,209,79,"[Poison, Ground]",267,259,220,...,209,[Poison],337,119,182,270,200,103,[Psychic],2
8,267,134,201,240,182,208,"[Electric, Ground]",249,160,236,...,169,"[Fire, Flying]",231,246,144,144,128,267,[Water],1
9,263,235,156,125,140,204,"[Normal, Flying]",309,208,208,...,113,"[Ground, Rock]",277,149,253,190,161,219,"[Steel, Fighting]",1

In [12]:
df.winner.value_counts(normalize=True)

winner
2    0.518758
1    0.481242
Name: proportion, dtype: float64

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4798 entries, 0 to 4797
Data columns (total 85 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   p1_mon1_hp     4798 non-null   int64
 1   p1_mon1_atk    4798 non-null   int64
 2   p1_mon1_def    4798 non-null   int64
 3   p1_mon1_spa    4798 non-null   int64
 4   p1_mon1_spd    4798 non-null   int64
 5   p1_mon1_spe    4798 non-null   int64
 6   p1_mon1_types  4798 non-null   object
 7   p1_mon2_hp     4798 non-null   int64
 8   p1_mon2_atk    4798 non-null   int64
 9   p1_mon2_def    4798 non-null   int64
 10  p1_mon2_spa    4798 non-null   int64
 11  p1_mon2_spd    4798 non-null   int64
 12  p1_mon2_spe    4798 non-null   int64
 13  p1_mon2_types  4798 non-null   object
 14  p1_mon3_hp     4798 non-null   int64
 15  p1_mon3_atk    4798 non-null   int64
 16  p1_mon3_def    4798 non-null   int64
 17  p1_mon3_spa    4798 non-null   int64
 18  p1_mon3_spd    4798 non-null   int64
 19  p1_mon3_spe    4798 non-null   int64
 20  p1_mon3_types  4798 non-null   object
 21  p1_mon4_hp     4798 non-null   int64
 22  p1_mon4_atk    4798 non-null   int64
 23  p1_mon4_def    4798 non-null   int64
 24  p1_mon4_spa    4798 non-null   int64
 25  p1_mon4_spd    4798 non-null   int64
 26  p1_mon4_spe    4798 non-null   int64
 27  p1_mon4_types  4798 non-null   object
 28  p1_mon5_hp     4798 non-null   int64
 29  p1_mon5_atk    4798 non-null   int64
 30  p1_mon5_def    4798 non-null   int64
 31  p1_mon5_spa    4798 non-null   int64
 32  p1_mon5_spd    4798 non-null   int64
 33  p1_mon5_spe    4798 non-null   int64
 34  p1_mon5_types  4798 non-null   object
 35  p1_mon6_hp     4798 non-null   int64
 36  p1_mon6_atk    4798 non-null   int64
 37  p1_mon6_def    4798 non-null   int64
 38  p1_mon6_spa    4798 non-null   int64
 39  p1_mon6_spd    4798 non-null   int64
 40  p1_mon6_spe    4798 non-null   int64
 41  p1_mon6_types  4798 non-null   object
 42  p2_mon1_hp     4798 non-null   int64
 43  p2_mon1_atk    4798 non-null   int64
 44  p2_mon1_def    4798 non-null   int64
 45  p2_mon1_spa    4798 non-null   int64
 46  p2_mon1_spd    4798 non-null   int64
 47  p2_mon1_spe    4798 non-null   int64
 48  p2_mon1_types  4798 non-null   object
 49  p2_mon2_hp     4798 non-null   int64
 50  p2_mon2_atk    4798 non-null   int64
 51  p2_mon2_def    4798 non-null   int64
 52  p2_mon2_spa    4798 non-null   int64
 53  p2_mon2_spd    4798 non-null   int64
 54  p2_mon2_spe    4798 non-null   int64
 55  p2_mon2_types  4798 non-null   object
 56  p2_mon3_hp     4798 non-null   int64
 57  p2_mon3_atk    4798 non-null   int64
 58  p2_mon3_def    4798 non-null   int64
 59  p2_mon3_spa    4798 non-null   int64
 60  p2_mon3_spd    4798 non-null   int64
 61  p2_mon3_spe    4798 non-null   int64
 62  p2_mon3_types  4798 non-null   object
 63  p2_mon4_hp     4798 non-null   int64
 64  p2_mon4_atk    4798 non-null   int64
 65  p2_mon4_def    4798 non-null   int64
 66  p2_mon4_spa    4798 non-null   int64
 67  p2_mon4_spd    4798 non-null   int64
 68  p2_mon4_spe    4798 non-null   int64
 69  p2_mon4_types  4798 non-null   object
 70  p2_mon5_hp     4798 non-null   int64
 71  p2_mon5_atk    4798 non-null   int64
 72  p2_mon5_def    4798 non-null   int64
 73  p2_mon5_spa    4798 non-null   int64
 74  p2_mon5_spd    4798 non-null   int64
 75  p2_mon5_spe    4798 non-null   int64
 76  p2_mon5_types  4798 non-null   object
 77  p2_mon6_hp     4798 non-null   int64
 78  p2_mon6_atk    4798 non-null   int64
 79  p2_mon6_def    4798 non-null   int64
 80  p2_mon6_spa    4798 non-null   int64
 81  p2_mon6_spd    4798 non-null   int64
 82  p2_mon6_spe    4798 non-null   int64
 83  p2_mon6_types  4798 non-null   object
 84  winner         4798 non-null   int64
dtypes: int64(73), object(12)
memory usage: 3.1+ MB